config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#new'
  mount Ckeditor::Engine => '/ckeditor'
  resources :pages
  get '/:id' => 'pages#show', as: :one_page



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Dragonfly

  dragonfly_accessor :data, app: :ckeditor
  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  validates_property :ext, of: :data, in: attachment_file_types unless attachment_file_types.empty?

  def url_thumb
    Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  validates_property :format, of: :data, in: image_file_types unless image_file_types.empty?
  validates_property :image?, of: :data, as: true, message: :invalid

  def url_content
    data.thumb('800x800>').url
  end

  def url_thumb
    data.thumb('118x100#').url(url_thumb_options)
  end
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates :title, presence: true
  validates :title, length: {maximum: 140}
  validates :title, uniqueness: true

  def generate_password
    massive = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a 
    pass = massive.shuffle[0..8].join
  end

  def encode_password(pass)
    Digest::SHA2.new(256).hexdigest(pass.to_s)
  end

  def password_valid?(pass_for_editing)
    password == encode_password(pass_for_editing)
  end

  def should_generate_new_friendly_id?
       slug.blank? || title_changed?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update]

  def index
    @pages = Page.all
  end

  def show
    
  end

  def new
    @page = Page.new  
  end

  def edit
  end

  def create
    @page = Page.new(page_params)
    password = @page.generate_password
    @page.password = @page.encode_password(password)
    if @page.save
      redirect_to @page, notice: "Your password #{password} for editing"
    else
      render :new
  end
      
  end
  def update
    if @page.password_valid?(password_params[:password])
      if @page.update(page_params)
        redirect_to one_page_path(id: @page.friendly_id), notice: "Successful"
      else
        redirect_to one_page_path, notice: "Not updated"
      end
    else
      redirect_to one_page_path, notice: "Password incorrect"
    end
  end

  private 

  def set_page
    @page = Page.friendly.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :data)
  end

  def password_params
    params.require(:page).permit(:password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/pages_helper.rb
module PagesHelper
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PageCreator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>
      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end%>

  <%= javascript_include_tag 'Ckeditor.cdn_url'%>
  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
     <%= f.cktext_area :data,  ckeditor: { language: 'en'} %>
  </div>
  <br>
  <% if action_name == "edit" %>
  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password, :value => ''%>
  </div>
  <% end %>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="button">
    <%= link_to 'Back', :back %>  
  </div>
<% end %>

app/views/pages/edit.html.erb
<%= render 'form', page: @page %>

<% link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<% @pages.each do |page|%>
<output>
<h3>
<%= link_to page.title, one_page_path(page) %>  
</h3>
  <br>
</output>
<% end %>

app/views/pages/new.html.erb
<%= link_to 'All pages', pages_path %> 

<h3>Create a new page</h3>


<%= render 'form', page: @page %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'All pages', pages_path %> 
<br>
<br>
<div class="">
  <%= @page.title %>
  <%= link_to 'Edit', edit_page_path(@page)%>
</div>
<%= raw @page.data %>